apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topolvm-immediate
provisioner: topolvm.io
parameters:
  "csi.storage.k8s.io/fstype": "xfs"
volumeBindingMode: Immediate
reclaimPolicy: Delete