prometheusOperator:
  securityContext:
    fsGroup: null
    runAsGroup: null
    runAsNonRoot: true
    runAsUser: null
    seccompProfile:
      type: RuntimeDefault
  admissionWebhooks:
    deployment:
      securityContext:
        fsGroup: null
        runAsGroup: null
        runAsNonRoot: true
        runAsUser: null
        seccompProfile:
          type: RuntimeDefault
    patch:
      securityContext:
        runAsGroup: null
        runAsNonRoot: true
        runAsUser: null
        seccompProfile:
          type: RuntimeDefault


prometheus:
  prometheusSpec:
    securityContext:
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: null
      fsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
