grafana:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
alertmanager:
  enabled: false
thanosRuler:
  enabled: false

prometheusOperator:
  securityContext:
    fsGroup: null
    runAsGroup: null
    runAsNonRoot: true
    runAsUser: null
    seccompProfile:
      type: RuntimeDefault
  admissionWebhooks:
    deployment:
      securityContext:
        fsGroup: null
        runAsGroup: null
        runAsNonRoot: true
        runAsUser: null
        seccompProfile:
          type: RuntimeDefault
    patch:
      securityContext:
        runAsGroup: null
        runAsNonRoot: true
        runAsUser: null
        seccompProfile:
          type: RuntimeDefault


prometheus:
  prometheusSpec:
    securityContext:
      runAsGroup: null
      runAsNonRoot: true
      runAsUser: null
      fsGroup: null
      seccompProfile:
        type: RuntimeDefault
