config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Bluebit-Innovations/bitblocks-k8s-gitops-local
      targetRevision: main


applications:
  - name: local-prometheus-stack
    namespace: monitoring
    chart: kube-prometheus-stack
    project: k8s-local
    sourceHelm: true
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 80.14.4
    tool:
      helm:
        releaseName: local-prometheus-stack
        valueFiles:
          - charts/local-prometheus-stack/values.yaml 
        
